
ITBOX_HEADERS = {
    "Accept": "application/x-clarity-gzip",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
    "Connection": "keep-alive",
    "Content-Length": "274",
    "Cookie": "MUID=2771B5AE5BB860E0086FA6D45A126134",
    "Host": "p.clarity.ms",
    "Origin": "https://www.itbox.ua",
    "Referer": "https://www.itbox.ua/ua/search/?Search=wacom",
    "Sec-Ch-Ua": "\"Google Chrome\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\"",
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": "\"macOS\"",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "cross-site",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Allow-Headers": "Chrome-bug,DNT,X-BRAIN-UA-TOKEN,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-CSRF-Token",
    "Access-Control-Allow-Methods": "GET, POST, DELETE, OPTIONS",
    "Access-Control-Allow-Origin": "https://www.itbox.ua",
    "Cache-Control": "max-age=31536000",
    "Content-Type": "image/svg+xml",
    "Date": "Tue, 11 Jun 2024 15:44:12 GMT",
    "Etag": "W/\"63aaf1f3-1e781\"",
    "Expires": "Wed, 11 Jun 2025 15:44:12 GMT",
    "Last-Modified": "Tue, 27 Dec 2022 13:24:03 GMT",
    "Server": "nginx",
    "Vary": "Accept-Encoding"
}