version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: django-container
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - scraping_network

#  bot:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    container_name: telegram_bot
#    env_file:
#      - .env
#    volumes:
#      - .:/app
#    ports:
#      - "2222:2222"
#    networks:
#      - scraping_network


  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - scraping_network

  db:
    container_name: db
    image: postgres:17.0-alpine
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - scraping_network
    restart: always

volumes:
  data:

networks:
  scraping_network:
    driver: bridge
