
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: django-container
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    networks:
      - scraping_network
    depends_on:
      - db
      - redis
    command: sh ./entrypoint.sh

  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - scraping_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_container
    restart: always
    command: celery -A scraper.celery_config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - django
    volumes:
      - .:/app
    networks:
      - scraping_network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat_container
    restart: always
    command: celery -A scraper.celery_config beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - django
    volumes:
      - .:/app
    networks:
      - scraping_network

volumes:
  postgres_data:
  redis_data:
  media_data:

networks:
  scraping_network:
    driver: bridge
