name: Deploy with Docker Compose

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Подключаемся к серверу через SSH
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22  # Если у вас нестандартный порт, замените на нужный
        script: |
          cd /path/to/your/docker-compose  # Папка с файлом docker-compose.yml
          git pull origin main  # Обновляем репозиторий с кодом
          docker-compose down   # Останавливаем текущие контейнеры
          docker-compose pull   # Загружаем новые образы (если изменились)
          docker-compose up -d  # Перезапускаем контейнеры
          docker system prune -f  # (Опционально) Удаляем старые образы и контейнеры
