# Generated by Django 4.2.10 on 2025-04-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'Історія цін', 'verbose_name_plural': 'Історії цін'},
        ),
    ]
