# Generated by Django 5.1 on 2025-03-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'Історія цін', 'verbose_name_plural': 'Історії цін'},
        ),
    ]
