# Generated by Django 5.1.3 on 2024-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_scrapeditem_remove_scrapeddata_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeditem',
            name='article',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
