# Generated by Django 5.1.3 on 2024-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_alter_scrapeditem_article_alter_scrapeditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeditem',
            name='article',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
