# Generated by Django 5.1.3 on 2024-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_alter_scrapeditem_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
