# Generated by Django 5.1.3 on 2024-12-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_partner_slug'),
        ('items', '0003_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.brand'),
        ),
    ]
